version: '3.8'
services:


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.3
    container_name: logstash
    volumes:
      - ./nginx:/var/log/nginx
      #- ./logstash/pipeline:/usr/share/logstash/config
      #- ./logstash/config/pipeline.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline/
   
    ports:
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    volumes:
      #- esdata:/usr/share/elasticsearch/data
      - ./nginx:/var/log/nginx
    networks:
      - elk


  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
    - ./nginx:/var/log/nginx/
    ports:
      - 8080:80

volumes:
  esdata:
networks:
  elk:
    driver: bridge